tab_spaces = 2
hard_tabs = false
newline_style = "Auto"
reorder_imports = true
reorder_modules = true
fn_params_layout = "Tall"
max_width = 120
use_small_heuristics = "Max"
fn_args_layout = "Compressed"
type_layout = "Compressed"
array_width = 1
